apiVersion: v1
kind: Service
metadata:
  name: {{ include "mocko.core.fullname" . }}
  labels:
    {{- include "mocko.core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.core.service.type }}
  ports:
    - port: {{ .Values.core.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mocko.core.selectorLabels" . | nindent 4 }}
