version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379:0
    ports:
      - "8085:8081"

  mocko-content:
    image: 'gabrielctpinheiro/mocko-proxy:1.7.3'
    environment:
      - PROXY_BASE-URI=
    ports:
      - '6625:8080'
    volumes:
      - './test/mocks/content:/home/mocko/mocks'
