version: '2'

services:
  redis:
    image: 'redis:6-alpine'
    ports:
      - '6379:6379'

  mocko-api:
    build: '../mocko-api'
    environment:
      - REDIS_HOST=redis

  meta-mocko-proxy:
    image: 'gabrielctpinheiro/mocko-proxy:1.8.0'
    environment:
      - PROXY_BASE-URI=http://mocko-api:8080
    ports:
      - '8081:8080'
    volumes:
      - './mocks.hcl:/home/mocko/mocks/mocks.hcl'
