name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Building services
      run: cd e2e-tests; docker compose build --parallel
    - name: Spinning services up
      run: cd e2e-tests; docker compose up -d
    - name: Preparing tests
      run: cd e2e-tests; npm install
    - name: Testing
      run: cd e2e-tests; npm test

  proxy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Spinning dependencies up
      run: cd mocko-proxy; docker compose up -d
    - name: Preparing tests
      run: cd mocko-proxy; npm install
    - name: Testing
      run: cd mocko-proxy; npm test
